import type { ProviderInsert, ModelInsert } from './schema.js';

export const seedProviders: ProviderInsert[] = [
  {
    id: 'anthropic',
    name: 'anthropic',
    displayName: 'Anthropic',
    baseUrl: 'https://api.anthropic.com',
    apiKeyEnvVar: 'ANTHROPIC_API_KEY',
    isLocal: false,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'openai',
    name: 'openai',
    displayName: 'OpenAI',
    baseUrl: 'https://api.openai.com',
    apiKeyEnvVar: 'OPENAI_API_KEY',
    isLocal: false,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'azure',
    name: 'azure',
    displayName: 'Azure OpenAI',
    baseUrl: process.env.AZURE_OPENAI_ENDPOINT || 'https://{resource}.openai.azure.com',
    apiKeyEnvVar: 'AZURE_OPENAI_KEY',
    isLocal: false,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'vertex',
    name: 'vertex',
    displayName: 'Google Vertex AI',
    baseUrl: 'https://{location}-aiplatform.googleapis.com/v1',
    apiKeyEnvVar: 'VERTEX_AI_API_KEY',
    isLocal: false,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'bedrock',
    name: 'bedrock',
    displayName: 'AWS Bedrock',
    baseUrl: 'https://bedrock.{region}.amazonaws.com',
    apiKeyEnvVar: 'AWS_SECRET_ACCESS_KEY',
    isLocal: false,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'ollama',
    name: 'ollama',
    displayName: 'Ollama (Local)',
    baseUrl: process.env.OLLAMA_BASE_URL || 'http://localhost:11434',
    apiKeyEnvVar: '',
    isLocal: true,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'lmstudio',
    name: 'lmstudio',
    displayName: 'LM Studio (Local)',
    baseUrl: process.env.LM_STUDIO_BASE_URL || 'http://localhost:1234',
    apiKeyEnvVar: '',
    isLocal: true,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'groq',
    name: 'groq',
    displayName: 'Groq',
    baseUrl: 'https://api.groq.com',
    apiKeyEnvVar: 'GROQ_API_KEY',
    isLocal: false,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'perplexity',
    name: 'perplexity',
    displayName: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    apiKeyEnvVar: 'PERPLEXITY_API_KEY',
    isLocal: false,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mistral',
    name: 'mistral',
    displayName: 'Mistral AI',
    baseUrl: 'https://api.mistral.ai',
    apiKeyEnvVar: 'MISTRAL_API_KEY',
    isLocal: false,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const seedModels: ModelInsert[] = [
  // Anthropic models
  {
    id: 'claude-3-5-sonnet',
    providerId: 'anthropic',
    name: 'claude-3-5-sonnet-20241022',
    displayName: 'Claude 3.5 Sonnet',
    contextWindow: 200000,
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { latest: true, reasoning: false },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'claude-3-5-haiku',
    providerId: 'anthropic',
    name: 'claude-3-5-haiku-20241022',
    displayName: 'Claude 3.5 Haiku',
    contextWindow: 200000,
    inputCostPer1M: 0.8,
    outputCostPer1M: 4.0,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { latest: true, reasoning: false },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'claude-3-opus',
    providerId: 'anthropic',
    name: 'claude-3-opus',
    displayName: 'Claude 3 Opus',
    contextWindow: 200000,
    inputCostPer1M: 15.0,
    outputCostPer1M: 75.0,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { latest: true, reasoning: false },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'claude-3-sonnet',
    providerId: 'anthropic',
    name: 'claude-3-sonnet-20240229',
    displayName: 'Claude 3 Sonnet',
    contextWindow: 200000,
    inputCostPer1M: 3.0,
    outputCostPer1M: 15.0,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'beta',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // OpenAI models
  {
    id: 'gpt-4o',
    providerId: 'openai',
    name: 'gpt-4o',
    displayName: 'GPT-4o',
    contextWindow: 128000,
    inputCostPer1M: 5.0,
    outputCostPer1M: 15.0,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { latest: true },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpt-4o-mini',
    providerId: 'openai',
    name: 'gpt-4o-mini',
    displayName: 'GPT-4o Mini',
    contextWindow: 128000,
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.60,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { latest: true },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpt-4-turbo',
    providerId: 'openai',
    name: 'gpt-4-turbo-2024-04-09',
    displayName: 'GPT-4 Turbo',
    contextWindow: 128000,
    inputCostPer1M: 10.0,
    outputCostPer1M: 30.0,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gpt-3.5-turbo',
    providerId: 'openai',
    name: 'gpt-3.5-turbo',
    displayName: 'GPT-3.5 Turbo',
    contextWindow: 16385,
    inputCostPer1M: 0.5,
    outputCostPer1M: 1.5,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: true,
    status: 'deprecated',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Google Vertex AI models
  {
    id: 'gemini-1.5-pro',
    providerId: 'vertex',
    name: 'gemini-1.5-pro-002',
    displayName: 'Gemini 1.5 Pro',
    contextWindow: 1000000,
    inputCostPer1M: 1.25,
    outputCostPer1M: 5.0,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { latest: true },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gemini-1.5-flash',
    providerId: 'vertex',
    name: 'gemini-1.5-flash-002',
    displayName: 'Gemini 1.5 Flash',
    contextWindow: 1000000,
    inputCostPer1M: 0.075,
    outputCostPer1M: 0.30,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { latest: true },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'gemini-1.0-pro',
    providerId: 'vertex',
    name: 'gemini-1.0-pro-001',
    displayName: 'Gemini 1.0 Pro',
    contextWindow: 32768,
    inputCostPer1M: 0.25,
    outputCostPer1M: 0.75,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'deprecated',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // AWS Bedrock models
  {
    id: 'claude-bedrock',
    providerId: 'bedrock',
    name: 'anthropic.claude-3-sonnet-20240229-v1:0',
    displayName: 'Claude 3 Sonnet (Bedrock)',
    contextWindow: 200000,
    inputCostPer1M: 2.5,
    outputCostPer1M: 12.5,
    supportsStreaming: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'llama3-bedrock',
    providerId: 'bedrock',
    name: 'meta.llama3-70b-instruct-v1:0',
    displayName: 'Llama 3 70B (Bedrock)',
    contextWindow: 8192,
    inputCostPer1M: 2.0,
    outputCostPer1M: 2.0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: false,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mistral-bedrock',
    providerId: 'bedrock',
    name: 'mistral.mistral-7b-instruct-v0:2',
    displayName: 'Mistral 7B (Bedrock)',
    contextWindow: 8192,
    inputCostPer1M: 0.15,
    outputCostPer1M: 0.15,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: false,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Ollama local models
  {
    id: 'llama3-ollama',
    providerId: 'ollama',
    name: 'llama3',
    displayName: 'Llama 3',
    contextWindow: 8192,
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: false,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mistral-ollama',
    providerId: 'ollama',
    name: 'mistral',
    displayName: 'Mistral',
    contextWindow: 8192,
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: false,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'codellama-ollama',
    providerId: 'ollama',
    name: 'codellama',
    displayName: 'Code Llama',
    contextWindow: 8192,
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: false,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'phi3-ollama',
    providerId: 'ollama',
    name: 'phi3',
    displayName: 'Phi-3',
    contextWindow: 4096,
    inputCostPer1M: 0,
    outputCostPer1M: 0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: false,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Groq models
  {
    id: 'llama3-8b-groq',
    providerId: 'groq',
    name: 'llama-3.1-8b-instant',
    displayName: 'Llama 3.1 8B (Groq)',
    contextWindow: 8192,
    inputCostPer1M: 0.05,
    outputCostPer1M: 0.08,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { fast: true },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mixtral-8x7b-groq',
    providerId: 'groq',
    name: 'mixtral-8x7b-32768',
    displayName: 'Mixtral 8x7B (Groq)',
    contextWindow: 32768,
    inputCostPer1M: 0.24,
    outputCostPer1M: 0.24,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: { fast: true },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Perplexity models
  {
    id: 'sonar-perplexity',
    providerId: 'perplexity',
    name: 'sonar',
    displayName: 'Sonar (Perplexity)',
    contextWindow: 128000,
    inputCostPer1M: 1.0,
    outputCostPer1M: 1.0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: false,
    status: 'active',
    metadata: { online: true },
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'sonar-pro-perplexity',
    providerId: 'perplexity',
    name: 'sonar-pro',
    displayName: 'Sonar Pro (Perplexity)',
    contextWindow: 200000,
    inputCostPer1M: 3.0,
    outputCostPer1M: 3.0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: false,
    status: 'active',
    metadata: { online: true },
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Mistral models
  {
    id: 'mistral-large',
    providerId: 'mistral',
    name: 'mistral-large-latest',
    displayName: 'Mistral Large',
    contextWindow: 128000,
    inputCostPer1M: 2.0,
    outputCostPer1M: 6.0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mistral-small',
    providerId: 'mistral',
    name: 'mistral-small-latest',
    displayName: 'Mistral Small',
    contextWindow: 32000,
    inputCostPer1M: 0.2,
    outputCostPer1M: 0.6,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: true,
    status: 'active',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'codestral',
    providerId: 'mistral',
    name: 'codestral-latest',
    displayName: 'Codestral',
    contextWindow: 32000,
    inputCostPer1M: 1.0,
    outputCostPer1M: 3.0,
    supportsStreaming: true,
    supportsVision: false,
    supportsFunctionCalling: true,
    status: 'beta',
    metadata: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];